development:
  adapter: postgresql
  encoding: unicode

  database: uwcshop_development
  pool: 5
  username: postgres
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: postgres
  password:
